### PR TITLE
Add TNP Bible module

### PR DESCRIPTION
**Pull request by LukeWhaskavsky**

### CODE REVIEW

**Comment by tuomas2** [comment]
> "Automatically generated on 2022-04-17 from source files MyBible"

How does MyBible module itself work in AndBible? Better or worse?

**Comment by tuomas2** [comment]
Thank you for doing this! 
Have you checked if this is permitted to be distributed?

**Comment by tuomas2** [comment]
Second question: Have you tried/ considered trying to get this to Crosswire repository?  See https://github.com/AndBible/and-bible/wiki/FAQ#please-add-module-x-to-andbible

Anwyay, I can put this to AndBible repository if this is "sound" translation and there's no permission issues.

**Comment by LukeWhaskavsky** [comment]
> Thank you for doing this! 
> Have you checked if this is permitted to be distributed?

Yes, the publisher allows free distribution in its entirety.  Besides, the module was created in cooperation with the publisher.

**Comment by tuomas2** [comment]
> > Thank you for doing this!
> > Have you checked if this is permitted to be distributed?
> 
> Yes, the publisher allows free distribution in its entirety. Besides, the module was created in cooperation with the publisher.

Then why not publishing with CrossWire?

**Comment by LukeWhaskavsky** [comment]
> Second question: Have you tried/ considered trying to get this to Crosswire repository?

I did not try.

> Anwyay, I can put this to AndBible repository if this is "sound" translation and there's no permission issues.

If you have doubts, you can download the pdf file from the publisher's official website https://swch.pl/tnp/index.html and on page 4 of this file you will find information:
"Wydawca wyraża zgodę na kopiowanie i rozpowszechnianie całości lub części publikacji wyłącznie w formie elektronicznej, jednak bez czerpania z tego korzyści finansowych i bez wprowadzania jakichkolwiek zmian w tekście."

**Comment by LukeWhaskavsky** [comment]
> > "Automatically generated on 2022-04-17 from source files MyBible"
> 
> How does MyBible module itself work in AndBible? Better or worse? 

The main text of the MyBible module is ok. Handling of Strong's numbers needs improvement.  
The footnotes in the TNP.commentaries.SQLite3 file are missing.
Highlighting Christ's words in red doesn't work either.

**Comment by LukeWhaskavsky** [comment]
> > > Thank you for doing this!
> > > Have you checked if this is permitted to be distributed?
> > 
> > Yes, the publisher allows free distribution in its entirety. Besides, the module was created in cooperation with the publisher.
> 
> Then why not publishing with CrossWire?

This is not yet a complete translation of the Bible.  When all the books are translated and the project is finished, I will send it to CrossWire.

**Comment by tuomas2** [comment]
Thank you! Merged now and checked that it works.

**Pull request merged**
