### PR TITLE
TNP module update

### PR DESCRIPTION
**Pull request by LukeWhaskavsky**
Bugs have been fixed and the latest translation improvements have been made.

### CODE REVIEW

**Comment by tuomas2** [comment]
Are you the original author of the module? Where is the OSIS source code (that could be indicated in config file)?

**Comment by LukeWhaskavsky** [comment]
Yes, I am the author of the module and the OSIS source file is on my disk.

**Comment by tuomas2** [comment]
Are you planning / willing to distribute OSIS source too? I recommend making a Github repository for it.

**Comment by LukeWhaskavsky** [comment]
The OSIS source file is converted from a google sheet and I have no plans to make it publicly available.

**Comment by tuomas2** [comment]
Okay. Why I'm recommending it is that if someone wants to further improve it in the future or rebuild it for some reason it would make it possible. But it's your decision. 

Checking and then publishing the module is in my roadmap (estimate 1-2 weeks).

**Comment by tuomas2** [comment]
Sorry thta this has been delayed and I am running out of time for today. 1-2 weeks more... :-/

**Comment by tuomas2** [comment]
Checked module and it looks good, so merging. Thank you!

**Pull request merged**
